use_frameworks!

target 'HTRouter_Example' do
  pod 'HTRouter', :path => '../'

  target 'HTRouter_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
